### ISSUE TITLE
Pybricks mode - reset angle

### ISSUE THREAD

**Issue by mrfabroa** [QuirkyCort/gears#113]
When running in Pybricks mode, usage of `reset_angle()`causes an error `reset_angle() missing 1 required argument` since the generated code is `reset_angle()` and not ``reset_angle(0)`

**Comment by QuirkyCort** [comment]
You're right. Personally, I find it strange that the pybricks api for reset_angle is "reset_angle(angle)" and not "reset_angle(angle=0)". Anyway, I'll fix the generated code first.

Subsequently, I'll change the api in Gears to "reset_angle(angle)", but not immediately as this will break compatibility with older code.
