### ISSUE TITLE
Initial gyro angle in arena non-zero

### ISSUE THREAD

**Issue by sgmurray** [QuirkyCort/gears#127]
Steps to reproduce.

1. Write a program to print the gyro angle.
2. Run the program in single player mode. Notice that regardless of starting position/orientation  the program will print a angle of zero.
3. Run the same program in arena mode. Notice that the program can give different non zero angles based on starting orientation.

**Comment by QuirkyCort** [comment]
In arena mode, I miss out resetting the gyro on start. Should be fixed now.

**Comment by sgmurray** [comment]
Yes. The website is working for me now. 
Thanks for fixing this so quickly!
