### ISSUE TITLE
Question: Zoom for python code

### ISSUE THREAD

**Issue by DJuego** [QuirkyCort/gears#20]
Is it possible to **zoom in/out** for ~~block and~~ python code? How? This is a critical feature when making presentations with a projector.

Thanks!

PD: Oops!!! The block code zoom was right under my nose! I am sorry!

![zoom for blocks code](https://user-images.githubusercontent.com/1956212/95850111-3d2b8200-0d48-11eb-9f9d-d4b255185cd1.png)

**Comment by QuirkyCort** [comment]
Just added a zoom function for Python. You can find it under the Python menu.

**Comment by DJuego** [comment]
I have already tested it. It works wonderfully! Thank you very much!  I close the thread since it has been resolved nicely.

DJuego
