### ISSUE TITLE
Save file to selected directory instead of browser default

### ISSUE THREAD

**Issue by stemrobotics** [QuirkyCort/gears#22]
When you load a file from a directory, it would be nice when you save it after modification, a save dialog appeared offering to save the file in the same location it came from or some other directory. If you are working on a program and saving on a regular basis saving to browser download directory and then moving the file to your source directory is a hassle.

**Comment by QuirkyCort** [comment]
I'm afraid that's not possible due to the browser's security restriction. Browsers do not allow a website to see which directory a file comes from, or control which directory a file is saved to.
