### ISSUE TITLE
it is no longer possible 'to overlap' hexahedrons in the worlds? (Oct 28 2020)

### ISSUE THREAD

**Issue by DJuego** [QuirkyCort/gears#26]
Sadly, it seems that with the last commit (Oct 28 2020) it is no longer possible to overlap hexahedrons in the worlds. Is this a intentional "fix"? This (anomalous) feature is "useful" due to the lack of more polyhedron types in Gears. :-(

DJuego

PS: I can add more examples if needed. :-)
![Gears (Oct 16, 2020)](https://user-images.githubusercontent.com/1956212/97498568-5ba69580-1964-11eb-86ba-434d780134ec.png)
![Gears (Oct 28, 2020)](https://user-images.githubusercontent.com/1956212/97498570-5c3f2c00-1964-11eb-9bee-ae1985b1c888.png)

**Comment by QuirkyCort** [comment]
You must be using the github version! A recent PR changed the units for rotation into degrees, breaking compatibility with previously created configuration files. I've just reverted it back to radians, so it should be fine now.

**Comment by DJuego** [comment]
Yes, yes. I was using  the github version! Sorry! The problem has been resolved with the last commit! Thanks again, @QuirkyCort  I close the issue!

DJuego
