### ISSUE TITLE
Question: How to add timers

### ISSUE THREAD

**Issue by MINTGenie** [QuirkyCort/gears#39]
Is it possible to add a timer or a stop watch or some counters to custom worlds. We felt the need for this during our competition.  Your suggestion would be helpful here.

**Comment by QuirkyCort** [comment]
Unfortunately, there are currently no ways to add a timer to the custom world. I'm gradually adding more capabilities to the image world and timer is likely to be added. But in the meantime, if you need more customization than what's currently possible, the best way is to create a new world in javascript.

**Comment by QuirkyCort** [comment]
There has been a big revamp of the custom world system and there is now an option to add a timer. Best way to add the timer is via the new World Builder.

The timer can be set to run upwards from zero or in a count down mode. Duration is configurable, and you can force the robots to stop automatically when the time runs out.
