### ISSUE TITLE
Bug: NaN for reset gyro!

### ISSUE THREAD

**Issue by DJuego** [QuirkyCort/gears#51]
When the gyro sensor is reset, the gyro sensor is unusable. :-O (!!)

![image](https://user-images.githubusercontent.com/1956212/104123933-d9642580-5345-11eb-8d06-241a0cbf5418.png)
![giro_reset](https://user-images.githubusercontent.com/1956212/104124011-44adf780-5346-11eb-9fbd-0a80373b6efd.gif)

DJuego

**Comment by QuirkyCort** [comment]
Should be fixed now.

**Comment by DJuego** [comment]
It works! Thank you for your swift fixing!! :-)

DJuego
