### ISSUE TITLE
The robot does not stop after passing the track 

### ISSUE THREAD

**Issue by CRcharo** [QuirkyCort/gears#55]
We programmed with students following the line last week on the simulator. We used a GPS sensor to measure the distance traveled on the y-axis. Everything worked normally last week. Today, when the specified distance is traveled, the robot does not stop. We tested various browsers and computers, tracks and robot settings on the simulator. Nothing helps. Where is the mistake? Will you help us please? 

![issue](https://user-images.githubusercontent.com/80464019/110791380-6e19cf80-8272-11eb-9ff0-4b7b20a8b047.png)
Last week
![issue2](https://user-images.githubusercontent.com/80464019/110792901-4297e480-8274-11eb-9d7b-7e03ae2deadf.png)

**Comment by sgmurray** [comment]
@CRcharo For a quick "fix" to your problem, try using altitude instead of y. 
@QuirkyCort Previous versions of virtual.py swapped the sensor's y and z to align with the world frame. The current version does not.

**Comment by CRcharo** [comment]
Thanks for quick idea. It seems that it works. In sensors window in simulator it is still Y. That's a little confusing. Thank you again very much.

**Comment by QuirkyCort** [comment]
Sorry about that. Made a mistake in an earlier commit. I've fixed it so that y will work correctly now.

**Comment by CRcharo** [comment]
@QuirkyCort Thanks a lot. We use your simulator at school to teach robotics, because now our schools are closed because of Covid-19. Really great job!!! Thank you very much again.

**Comment by QuirkyCort** [comment]
Glad it is useful for you!

Closing this issue.
