### ISSUE TITLE
Layout problems on small screen, e.g. world selection dialog has to large font compared to other UI parts

### ISSUE THREAD

**Issue by germanicianus** [QuirkyCort/gears#68]
See screenshot below. On small screens like phones have (even on an iPhone 7 Plus) this is a huge problem which OpenRoberta doesn't have.
![gears_layout_problem](https://user-images.githubusercontent.com/37223176/114285132-f7304c00-9a54-11eb-97dc-2dca3899c6f7.png)

**Comment by QuirkyCort** [comment]
I've put in a fix for that. The entire center section is scrollable now.

**Comment by germanicianus** [comment]
The font and the buttons are still really large compared to the main window, but the scrolling is fixed indeed. I didn't try it yet on real hardware.
![gears_sim_ios_landscape_select_world](https://user-images.githubusercontent.com/37223176/114312614-812ef200-9af3-11eb-9eda-1774274e3ffa.png)

**Comment by QuirkyCort** [comment]
Fonts are often not scaled to the screen dimensions, else it may be too small to read.

As long as there's no major usability concerns, I'll rather have larger fonts than smaller. Larger fonts helps with...

- Educators presenting to a class...
- Kids with small screen...
- Users with reading difficulties...

**Comment by germanicianus** [comment]
Agreed. But I think there should be some zoom buttons in the UI like the Simulator already has for the 3D representation. The reason is, that there are browsers on mobile devices which don't have controls for that, e.g. Amazon Silk on the Fire TV 4K - and the UI just looks HUGE on a 65 inch TV. Additionally, there should be a fullscreen toggle button for the same reason and also to save screen estate - especially on an iPhone in landscape mode because the tabs and URL bar occupy a lot of space and they cannot be hidden because there is no room to scroll down in the UI (which would hide it).
