### ISSUE TITLE
Show fps

### ISSUE THREAD

**Issue by germanicianus** [QuirkyCort/gears#71]
It's helpful for users to know the fps of the simulation, especially on older devices and with different browsers. _gears_ works on a _Fire TV Stick 4K Ultra HD_ in the default browser _Silk_, but feels a bit sluggish and the Bluetooth mouse is a bit laggy. When I use _Firefox for Fire TV_, the world feels quite smooth and the mouse is also more responsive, but the browser is [soon to be discontinued](https://support.mozilla.org/en-US/kb/end-support-firefox-amazon-devices). Therefore I installed and tried [Fennec from F-Droid](https://f-droid.org/de/packages/org.mozilla.fennec_fdroid/) which is based on the latest Firefox for Android. It is really responsive regarding the Bluetooth mouse (and requires one), but the world feels really slow.

I attached a patch ([gears_show_fps.zip](https://github.com/QuirkyCort/gears/files/6292145/gears_show_fps.zip)) with a hacky solution to show the fps which can be used as a starting point.
![gears_fps](https://user-images.githubusercontent.com/37223176/114310915-d7e4fd80-9aec-11eb-9716-5b59c661f4dd.png)

**Comment by QuirkyCort** [comment]
Added an option to display FPS. You can find it under Help.

**Comment by germanicianus** [comment]
Great! I just tested it. :)
