### ISSUE TITLE
Pause/stop Babylon rendering when Simulator invisible to save battery

### ISSUE THREAD

**Issue by germanicianus** [QuirkyCort/gears#75]
This is really important for mobile devices like tablets used in schools for education. ~ 40 % of my CPU/iGPU are used when just the block view is visible and I do nothing. When I used _gears_ on my phone, ~ 10 % of my battery were drain in a very short time.
![gears_cpu_usage_when_sim_invisible](https://user-images.githubusercontent.com/37223176/114620165-98b0db00-9cab-11eb-9cb5-98fbd40da1e3.png)

**Comment by QuirkyCort** [comment]
Modified it so that the 3D rendering will only run if the simulator tab is opened, or if the user's program is running.

**Comment by germanicianus** [comment]
Works -> Close issue. Implemented with https://github.com/QuirkyCort/gears/commit/cf1ae84c1338b441f9b724980bf68834ce66c44a.
