### ISSUE TITLE
Arena Mode Bots Tab Stays Up

### ISSUE THREAD

**Issue by sgmurray** [QuirkyCort/gears#78]
When I switch from the Bots tab to the Arena tab in Arena Mode, the Bots tab seems to stay open over the Arena. 
Note the white text of the  play button, stop button, World button, and Reset button over Player 0.

![image](https://user-images.githubusercontent.com/6422994/114768624-21288d80-9d37-11eb-8a89-8bdb0bf16f1e.png)

**Comment by QuirkyCort** [comment]
My bad. The changes for the FPS display and the suspension of rendering wasn't handled properly in arena.

Should be fine now.

**Comment by sgmurray** [comment]
That fixed it. Thanks!
