### ISSUE TITLE
Unable to upload zip files to Arena

### ISSUE THREAD

**Issue by sgmurray** [QuirkyCort/gears#81]
Uploading a zip file and clicking the checkbox in Arena mode bots tab gives an error. 

![Screenshot from 2021-05-05 00-43-56](https://user-images.githubusercontent.com/6422994/117097997-3fcce380-ad3b-11eb-9f2b-c31281faff98.png)

**Comment by QuirkyCort** [comment]
It's a race condition. Sometimes the render function will run before the robot is fully loaded.

I've put in some additional checks to prevent this. Should be ok now.

**Comment by sgmurray** [comment]
I am still able to trigger the race condition. 

self.leftWheel != null seems to work better than typeof self.leftWheel != 'undefined' in Robot.jsj

**Comment by QuirkyCort** [comment]
You're right. self.leftWheel is always defined, so I should be checking for null instead. I've fixed it.

Strangely enough, I couldn't trigger the problem after adding the type check. Probably just a coincidence...
