### ISSUE TITLE
Configurator Uncaught Type Error

### ISSUE THREAD

**Issue by sgmurray** [QuirkyCort/gears#88]
Steps to reproduce

1. Open up the robot configurator. (Notice how Body is highlighted in the left hand menu)
2. Click on the ground (Notice how Body is no longer highlighted in the left hand menu)
3. Change bodyHeight in the right hand menu. 
4. See the uncaught type error in the developer console.

Notice that you won't get an error if you change bodyHeight while Body is highlighted in the left hand menu.

**Comment by QuirkyCort** [comment]
Thanks. I've fixed it.
